# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\"/\n\x0fRegisterMessage\x12\x0e\n\x06ipaddr\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\")\n\x10RegisterResponse\x12\n\n\x02id\x18\x01 \x01(\r\x12\t\n\x01m\x18\x02 \x01(\r28\n\x05\x43hord\x12/\n\x08Register\x12\x10.RegisterMessage\x1a\x11.RegisterResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERMESSAGE._serialized_start=15
  _REGISTERMESSAGE._serialized_end=62
  _REGISTERRESPONSE._serialized_start=64
  _REGISTERRESPONSE._serialized_end=105
  _CHORD._serialized_start=107
  _CHORD._serialized_end=163
# @@protoc_insertion_point(module_scope)
