# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chord_pb2 as chord__pb2


class ChordStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/Chord/Register',
                request_serializer=chord__pb2.RegisterMessage.SerializeToString,
                response_deserializer=chord__pb2.RegisterResponse.FromString,
                )
        self.Deregister = channel.unary_unary(
                '/Chord/Deregister',
                request_serializer=chord__pb2.DeregisterMessage.SerializeToString,
                response_deserializer=chord__pb2.DeregisterResponse.FromString,
                )
        self.PopulateFingerTable = channel.unary_unary(
                '/Chord/PopulateFingerTable',
                request_serializer=chord__pb2.PopulateFingerTableMessage.SerializeToString,
                response_deserializer=chord__pb2.PopulateFingerTableResponse.FromString,
                )
        self.SaveData = channel.unary_unary(
                '/Chord/SaveData',
                request_serializer=chord__pb2.SaveDataMessage.SerializeToString,
                response_deserializer=chord__pb2.SaveDataResponse.FromString,
                )
        self.RemoveData = channel.unary_unary(
                '/Chord/RemoveData',
                request_serializer=chord__pb2.RemoveDataMessage.SerializeToString,
                response_deserializer=chord__pb2.RemoveDataResponse.FromString,
                )
        self.GetChordInfo = channel.unary_unary(
                '/Chord/GetChordInfo',
                request_serializer=chord__pb2.GetChordInfoMessage.SerializeToString,
                response_deserializer=chord__pb2.GetChordInfoResponse.FromString,
                )
        self.GetFingerTable = channel.unary_unary(
                '/Chord/GetFingerTable',
                request_serializer=chord__pb2.GetFingerTableMessage.SerializeToString,
                response_deserializer=chord__pb2.GetFingerTableResponse.FromString,
                )
        self.FindData = channel.unary_unary(
                '/Chord/FindData',
                request_serializer=chord__pb2.FindDataMessage.SerializeToString,
                response_deserializer=chord__pb2.FindDataResponse.FromString,
                )
        self.NotifySucc = channel.unary_unary(
                '/Chord/NotifySucc',
                request_serializer=chord__pb2.NotifySuccMessage.SerializeToString,
                response_deserializer=chord__pb2.NotifySuccResponse.FromString,
                )
        self.NotifyPred = channel.unary_unary(
                '/Chord/NotifyPred',
                request_serializer=chord__pb2.NotifyPredMessage.SerializeToString,
                response_deserializer=chord__pb2.NotifyPredResponse.FromString,
                )


class ChordServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PopulateFingerTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChordInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFingerTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifySucc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyPred(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=chord__pb2.RegisterMessage.FromString,
                    response_serializer=chord__pb2.RegisterResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=chord__pb2.DeregisterMessage.FromString,
                    response_serializer=chord__pb2.DeregisterResponse.SerializeToString,
            ),
            'PopulateFingerTable': grpc.unary_unary_rpc_method_handler(
                    servicer.PopulateFingerTable,
                    request_deserializer=chord__pb2.PopulateFingerTableMessage.FromString,
                    response_serializer=chord__pb2.PopulateFingerTableResponse.SerializeToString,
            ),
            'SaveData': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveData,
                    request_deserializer=chord__pb2.SaveDataMessage.FromString,
                    response_serializer=chord__pb2.SaveDataResponse.SerializeToString,
            ),
            'RemoveData': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveData,
                    request_deserializer=chord__pb2.RemoveDataMessage.FromString,
                    response_serializer=chord__pb2.RemoveDataResponse.SerializeToString,
            ),
            'GetChordInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChordInfo,
                    request_deserializer=chord__pb2.GetChordInfoMessage.FromString,
                    response_serializer=chord__pb2.GetChordInfoResponse.SerializeToString,
            ),
            'GetFingerTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFingerTable,
                    request_deserializer=chord__pb2.GetFingerTableMessage.FromString,
                    response_serializer=chord__pb2.GetFingerTableResponse.SerializeToString,
            ),
            'FindData': grpc.unary_unary_rpc_method_handler(
                    servicer.FindData,
                    request_deserializer=chord__pb2.FindDataMessage.FromString,
                    response_serializer=chord__pb2.FindDataResponse.SerializeToString,
            ),
            'NotifySucc': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifySucc,
                    request_deserializer=chord__pb2.NotifySuccMessage.FromString,
                    response_serializer=chord__pb2.NotifySuccResponse.SerializeToString,
            ),
            'NotifyPred': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyPred,
                    request_deserializer=chord__pb2.NotifyPredMessage.FromString,
                    response_serializer=chord__pb2.NotifyPredResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Chord', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chord(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/Register',
            chord__pb2.RegisterMessage.SerializeToString,
            chord__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/Deregister',
            chord__pb2.DeregisterMessage.SerializeToString,
            chord__pb2.DeregisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PopulateFingerTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/PopulateFingerTable',
            chord__pb2.PopulateFingerTableMessage.SerializeToString,
            chord__pb2.PopulateFingerTableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/SaveData',
            chord__pb2.SaveDataMessage.SerializeToString,
            chord__pb2.SaveDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/RemoveData',
            chord__pb2.RemoveDataMessage.SerializeToString,
            chord__pb2.RemoveDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChordInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/GetChordInfo',
            chord__pb2.GetChordInfoMessage.SerializeToString,
            chord__pb2.GetChordInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFingerTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/GetFingerTable',
            chord__pb2.GetFingerTableMessage.SerializeToString,
            chord__pb2.GetFingerTableResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/FindData',
            chord__pb2.FindDataMessage.SerializeToString,
            chord__pb2.FindDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifySucc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/NotifySucc',
            chord__pb2.NotifySuccMessage.SerializeToString,
            chord__pb2.NotifySuccResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyPred(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chord/NotifyPred',
            chord__pb2.NotifyPredMessage.SerializeToString,
            chord__pb2.NotifyPredResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
